spring:
  application:
    name: userService

  datasource:
    url: jdbc:postgresql://localhost:5432/taskFlow_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: qWERTYuiop1234567890qazxswedcvfrtgb
  lifetime: 30m

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
