spring:
  application:
    name: projectService

  datasource:
    url: jdbc:postgresql://localhost:5432/taskFlow_db
    driver-class-name: org.postgresql.Driver
    password: admin
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082